#cloud-config
package_upgrade: true

package_update: true

runcmd:
  - sudo swapoff -a #Deshabilitar el swapping memory
  - sudo mkdir /home/ubuntu/manifests
  - sudo mkdir -p /etc/containerd
  - containerd config default | sudo tee /etc/containerd/config.toml
  - |
    cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
    overlay
    br_netfilter
    EOF
  - sudo modprobe overlay
  - sudo modprobe br_netfilter
  - |
    cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
    net.bridge.bridge-nf-call-iptables  = 1
    net.ipv4.ip_forward                 = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    EOF
  - sudo sysctl --system
  # Instalación de kubeadm, kubelet y kubectl
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https ca-certificates curl
  - sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - sudo apt-get update
  - sudo apt-get install -y kubelet=1.22.0-00 kubeadm=1.22.0-00 kubectl=1.22.0-00
  - sudo apt-mark hold kubelet kubeadm kubectl
packages:
  - containerd

  # - [
  #     bash,
  #     -c,
  #     echo "this has been written via cloud-init" + $(date) >> /home/ubuntu/myScript.txt,
  #   ]
  # - |
  #   cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
  #   overlay
  #   br_netfilter
  #   EOF
